### ISSUE TITLE
Advantage of Linuxbrew over Chromebrew?

### ISSUE THREAD

**Issue by trusktr** [Linuxbrew/legacy-linuxbrew#1111]
Just curious to know why install Chromebrew in order to install Linuxbrew and then delete Chromebrew. It is obvious you prefer Linuxbrew. Why is that? (Just curious to learn something).

**Comment by sjackman** [comment]
@DoomHammer Piotr may be able to answer your question.

**Comment by DoomHammer** [comment]
I am not an expert on Chromebrew, but I believe it has been made in order to ease bootstrapping of Linuxbrew. Hopefully in a future such additional resources would no longer be needed.

If you have more specific questions, @trusktr please don't hesitate to ask. I am closing the ticket for now if you don't mind.
