### ISSUE TITLE
objective-caml install error

### ISSUE THREAD

**Issue by AndreTheHunter** [Linuxbrew/legacy-linuxbrew#304]
When trying to install objective-caml, I get the following error

```
brew install objective-caml
==> Downloading http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.1.tar.gz
Already downloaded: /home/andre/.cache/Homebrew/objective-caml-4.02.1.tar.gz
==> ./configure --prefix /home/andre/.linuxbrew --mandir /home/andre/.linuxbrew/Cellar/objective-caml/4.02.1_2/share
-aspp
/usr/bin/gcc-4.8 -Os -w -pipe -march=core2 -c
-no-graph

[ERROR!]Arguments to this script look like '-prefix /foo/bar', not '-prefix=/foo/bar' (note the '=').
```

[Gist here](https://gist.github.com/anonymous/e4b8ebac05fc8d5b6ee7)

**Comment by sjackman** [comment]
If you're able to troubleshoot and find a fix on your own, a pull request would be most welcome.

**Comment by ifigueroap** [comment]
I confirm that I'm getting the same issue on Ubuntu 14.04.2

**Comment by iggyvolz** [comment]
The problem seems to be that objective-caml strictly searches for any "=" and fails if it is in the configure, which IMO is a terrible practice decision.  This means that CFLAGS written directly in the script are impossible.  I tried to even quote the cflags to no avail, it will still fail.

Alternatives?  Exporting CFLAGS (terrible idea and not going to happen), writing them to a file and having bash strategically read them after the failing script goes through, or petitioning upstream to remove the strict ban.

**Comment by sjackman** [comment]
If we removed the configure argument `-march=core2` it would at least compile.

**Comment by iggyvolz** [comment]
The -march=core2 is within CFLAGS though - so you would have to run the compiler without any CFLAGS at all (which I believe would install outside linuxbrew).

**Comment by sjackman** [comment]
I'm suggesting that the `objective-caml` formula could remove `-march=core2` from `CFLAGS`. A very hacky workaround, but better than nothing, perhaps.
