### ISSUE TITLE
brew postinstall python3 fails

### ISSUE THREAD

**Issue by danielecook** [Linuxbrew/legacy-linuxbrew#571]
Not really sure what to make of this error - 

Error: undefined class/module Debrew::

Gist logs are available here:

https://gist.github.com/danielecook/767d789289d7857a9c5e

**Comment by rwhogg** [comment]
Sorry we only got back to you on this issue now. Does this still affect you?

**Comment by danielecook** [comment]
I switched to using pyenv (-; This doesn't affect me anymore.

**Comment by niemasd** [comment]
I'm having the same issue, any way you can still follow up? I can try using pyenv instead, but it would be nice to have python3 via brew

**Comment by sjackman** [comment]
Please report the output of `brew gist-logs python3`

**Comment by niemasd** [comment]
https://gist.github.com/anonymous/c03a501563ce727327f885d3e9a8e438

**Comment by sjackman** [comment]
```
/scratchfast/a1moshir/.linuxbrew/Cellar/python3/3.6.1/bin/python3
-s
setup.py
--no-user-cfg
install
--force
--verbose
--install-scripts=/scratchfast/a1moshir/.linuxbrew/Cellar/python3/3.6.1/bin
--install-lib=/scratchfast/a1moshir/.linuxbrew/lib/python3.6/site-packages
--single-version-externally-managed
--record=installed.txt

Failed to execute: /scratchfast/a1moshir/.linuxbrew/Cellar/python3/3.6.1/bin/python3
```
https://gist.githubusercontent.com/anonymous/c03a501563ce727327f885d3e9a8e438/raw/49340f56814d38f51d90fffe826c11e5abd47dd5/post_install.01.python3

**Comment by sjackman** [comment]
Please report…
```sh
brew list python3
ls -l /scratchfast/a1moshir/.linuxbrew/Cellar/python3/3.6.1/bin/python3
/scratchfast/a1moshir/.linuxbrew/Cellar/python3/3.6.1/bin/python3 --version
```

**Comment by niemasd** [comment]
Actually, I remember now that I had somewhat hackingly gotten things running by commenting out line 52 of `.linuxbrew/Library/Homebrew/os/linux/elf.rb`:

`raise ErrorDuringExecution, command unless $?.success?`

I had originally done that because I was getting the following error when installing glibc (a requirement of python3):

`Error: Failure while executing: ["ldd", "/scratchfast/a1moshir/.linuxbrew/Cellar/glibc/2.19/lib/libc-2.19.so"]`

Commenting out that line got me past glibc's installation, and I was able to successfully install other things that depended on glibc, but I'm guessing it broke things down the line. Perhaps I should create a new Issue for that instead? I'm guessing that fixing whatever was causing that error will (hopefully) fix the other issues?

**Comment by sjackman** [comment]
If you're able to reproduce your issue, please open a new issue at https://github.com/Linuxbrew/homebrew-core/issues
